codecov:
  max_report_age: off

comment: false

coverage:
  precision: 2
  round: down
  status:
    project:
      default:
       threshold: 0.2
       if_not_found: success
    patch:
      default:
        enabled: no
        if_not_found: success
    changes:
      default:
        enabled: no
        if_not_found: success
  ignore:
    - "src/server/index.js"
    - "src/utils/elasticSearch/searchQuery.js"
    - "src/utils/redis/redis.js"
